### ISSUE TITLE
Demo Room - Task - Fuse Box

### ISSUE THREAD

**Issue by cpaech** [TheBlackouts/The-Enlightenment#11]
Modelling a Fuse Box and Implementing it in Game.
Fuse Box will have approx. 4 Rows and 5 per Row fuses.
Different Sizes per Row (General Light is big, Fridge light is smaller...)

**Comment by cpaech** [comment]
![image](https://user-images.githubusercontent.com/67830148/179993509-061d03b4-5096-4b13-a00a-23c7f27bbad5.png)
First FuseBox Prototype, thinking about changing the Fuses

**Comment by Connrr** [comment]
Making The Smaller Sockets Different Shapes for the RoomLights as a sort of Progression System.
